# Generated by Django 5.1.7 on 2025-05-15 14:33

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0006_groupmessage_file_groupmessage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='file',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='image',
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
